version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    volumes:
      - ./backend/app:/code/app
    environment:
      DATABASE_URL: postgresql+psycopg2://username:password@db:5432/library_db
    ports:
      - "8000:8000"

  #frontend:
  #  build: ./frontend
  #  ports:
  #    - "4200:80"  # Adjust port if necessary

volumes:
  db_data: