/**
 * Library Web Application
 * A web application for library management.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryInBook } from './categoryInBook';


export interface Book { 
    title: string;
    author: string;
    isbn: string;
    publisher?: string | null;
    edition?: string | null;
    barcode: string;
    id: number;
    total_quantity: number;
    available_quantity: number;
    categories?: Array<CategoryInBook>;
}

