/**
 * Library Web Application
 * A web application for library management.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookInCategory { 
    id: number;
    title: string;
    author: string;
    isbn: string;
    barcode: string;
}

