/**
 * Library Web Application
 * A web application for library management.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInBorrow } from './userInBorrow';
import { BookInBorrow } from './bookInBorrow';


export interface Borrow { 
    user_id: number;
    book_id: number;
    reserve_date?: string | null;
    due_date?: string | null;
    return_date?: string | null;
    is_returned?: boolean | null;
    id: number;
    user: UserInBorrow;
    book: BookInBorrow;
}

