/**
 * Library Web Application
 * A web application for library management.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookInCategory } from './bookInCategory';


export interface Category { 
    name: string;
    id: number;
    books?: Array<BookInCategory>;
}

