/**
 * Library Web Application
 * A web application for library management.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserCreate { 
    username: string;
    role: string;
    first_name: string;
    last_name: string;
    address?: string | null;
    phone_number?: string | null;
    status?: string | null;
    password: string;
}

